[package]
name = "eval"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
board = {path = "../board"}
nalgebra = "0.32.3"
pathfinding = "4.3.0"
snake_tuner = "0.5.3"
toml = "0.7.6"