[package]
name = "minimax"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
board = {path = "../board"}
eval = {path = "../eval"}
pretty_assertions = "1.4.0"
